repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.72.1 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terragrunt_fmt
      name: Format Terragrunt
    - id: terraform_tflint
      name: Initialize tflint 
      args: 
        - --args=--init
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
    - id: terraform_tflint
      name: Validate Terraform using tflint (./)
      args: 
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
        - --args=__GIT_WORKING_DIR__/
    - id: terraform_tflint
      name: Validate Terraform using tflint (./test/stg1)
      args: 
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
        - --args=__GIT_WORKING_DIR__/test/stg1
    - id: terraform_tflint
      name: Validate Terraform using tflint (./test/test1)
      args: 
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
        - --args=__GIT_WORKING_DIR__/test/test1       
    - id: terraform_tflint
      name: Validate Terraform using tflint (./test/test2)
      args: 
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
        - --args=__GIT_WORKING_DIR__/test/test2            